require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - '!**/.rubocop.yml'
  DisplayCopNames: true
